### ISSUE TITLE
Add button to demo for new style

### ISSUE THREAD

**Issue by PetersonGIS** [go-spatial/tegola-web-demo#11]
New style here: https://github.com/go-spatial/tegola-web-demo/blob/master/styles/natural-earth-quickstart.json

Same style for both mapboxgl and openlayers.

**Comment by ARolek** [comment]
@justenPalmer can you take a look at this? Basically we want to add the Natural Earth style to the demo app.

**Comment by justenPalmer** [comment]
Added this as a new map at http://demo.tegola.io/ne.html
