### ISSUE TITLE
Parks rendering order

### ISSUE THREAD

**Issue by PetersonGIS** [go-spatial/tegola-web-demo#17]
Some parks appear to be superseded in draw order by other landuses such as residential in the higher zooms where most landuses are rendered. Some islands are not rendering at the lower zoom levels but appear at the higher zooms.
![park2](https://user-images.githubusercontent.com/5266205/36281510-287589b8-125b-11e8-9421-428b9bb8197d.JPG)
![park1](https://user-images.githubusercontent.com/5266205/36281512-288acd64-125b-11e8-83d7-a25b428a5e68.JPG)

**Comment by ARolek** [comment]
@PetersonGIS I wonder if this has to do with the order of the layers in the style definition?

**Comment by PetersonGIS** [comment]
Yes, I think you're right that it does. I am wondering if we should have a z_order on the landuse table like here: https://github.com/mapbox/osm-bright/blob/master/imposm-mapping.py#L315. 

But in the meantime it is also easy to separate out the type==park features and style them above the type==residential features in the style.json to at least fix the specific case shown in the screenshot where a residential polygon is rendering above a park polygon.

**Comment by PetersonGIS** [comment]
I moved the issue about the missing land/water islet over to https://github.com/go-spatial/tegola-web-demo/issues/19

**Comment by PetersonGIS** [comment]
This should be closed once https://github.com/go-spatial/tegola-web-demo/pull/23 is merged in.
