### ISSUE TITLE
Water_areas at/around zoom 16

### ISSUE THREAD

**Issue by PetersonGIS** [go-spatial/tegola-web-demo#19]
There is an islet at https://osm.tegola.io/#16.82/47.66416/9.17955 that has a hotel on it. This islet shows up correctly as land in **only** zoom 16. 

At lower zooms and higher zooms it is characterized as water in the water_areas table. Or at least that is how it is rendering, which is incorrect.

![water_areas_z16](https://user-images.githubusercontent.com/5266205/36318562-710ca52e-12fd-11e8-9b1c-abea3913d20f.JPG)
![water_areas_z15](https://user-images.githubusercontent.com/5266205/36318563-71214e02-12fd-11e8-83f2-cd8f99c36efb.JPG)
![water_areas_styled](https://user-images.githubusercontent.com/5266205/36318564-71396c6c-12fd-11e8-8754-fe9b685bb52c.JPG)
![water_areas_z17](https://user-images.githubusercontent.com/5266205/36318565-7152abaa-12fd-11e8-95f6-9c50e201ee7e.JPG)

**Comment by PetersonGIS** [comment]
also missing a couple small island features here
![sydneyislands](https://user-images.githubusercontent.com/5266205/36329455-3a66017a-1323-11e8-90f2-e37f32b53b7e.JPG)

**Comment by ARolek** [comment]
is this addressed in the PR that was recently merged?

**Comment by PetersonGIS** [comment]
Yes. This is resolved now.
![resolved](https://user-images.githubusercontent.com/5266205/38819973-0635891a-415a-11e8-8d5c-d0a05b7c137b.PNG)
