### ISSUE TITLE
Style pier landuse polygons like "earth"

### ISSUE THREAD

**Issue by nvkelso** [go-spatial/tegola-web-demo#5]
In the attached screen grab observe buildings and roads over the water. Instead they should be over a pier landuse polygon that’s styled like earth. Not clear if you have that data in the tiles already. 

I only know because someone from LA Times asked me to add / change to Tilezen earlier this year for their San Diego partners ;)

https://go-spatial.github.io/tegola-web-demo/?zoom=15&latitude=32.710504592752045&longitude=-117.16335890762434&bearing=0&pitch=0&theme=hot-osm&source=ec2&renderer=ol

<img width="514" alt="screen shot 2017-11-13 at 10 49 53" src="https://user-images.githubusercontent.com/853051/32743534-8b2c6494-c861-11e7-8d1b-aa9183d8766d.png">

**Comment by PetersonGIS** [comment]
Thanks for catching that, @nvkelso. 
TO DO: style other_areas, type = pier (other_lines, type = pier already styled, may need to be removed)

**Comment by PetersonGIS** [comment]
Resolved via https://github.com/go-spatial/tegola-web-demo/pull/7.

This seemed important enough to resolve despite the departure from the reference style (the humanitarian style at https://www.openstreetmap.org). 

![pierosm](https://user-images.githubusercontent.com/5266205/32970222-52db5ea0-cba5-11e7-8e09-ca9d50c7af72.PNG)
^Piers in the reference style

![pierfix](https://user-images.githubusercontent.com/5266205/32970229-5e6f4dd0-cba5-11e7-91af-c240b25825d1.PNG)
^Piers in our style, after the fix

**Comment by nvkelso** [comment]
Nice!
